### ISSUE TITLE
PlugIn make Homebridge Crash

### ISSUE THREAD

**Issue by RealLittleSherman** [smka/homebridge-broadlink-mp#11]
Hi, after installing this plugin my Homebridge begins crashed, i bought  an BroadLink MP1 and the homebridge.err file showme the following crash cause:

`crypto.js:181`
  `var ret = this._handle.final();`
                         `^`
`Error: error:0606508A:digital envelope routines:EVP_DecryptFinal_ex:data not multiple of block length
    at Decipheriv.final (crypto.js:181:26)`
    `at Socket.cs.on (/usr/lib/node_modules/homebridge-broadlink-platform/node_modules/broadlinkjs-sm/index.js:234:27)`
    `at emitTwo (events.js:125:13)`
    `at Socket.emit (events.js:213:7)`
    `at UDP.onMessage [as onmessage] (dgram.js:619:8)`

Can you helpme with this?

Thanks in advance

**Comment by iandronowicz** [comment]
exact same issue here....
