### ISSUE TITLE
Randomly Crash

### ISSUE THREAD

**Issue by ChordSolo** [smka/homebridge-broadlink-mp#22]
Hi @smka 

**crypto.js:183
  var ret = this._handle.final();
                         ^

Error: error:0606508A:digital envelope routines:EVP_DecryptFinal_ex:data not multiple of block length
    at Decipheriv.final (crypto.js:183:26)
    at Socket.cs.on (/usr/lib/node_modules/homebridge-broadlink-platform/node_modules/broadlinkjs-sm/index.js:234:27)
    at emitTwo (events.js:126:13)
    at Socket.emit (events.js:214:7)
    at UDP.onMessage [as onmessage] (dgram.js:659:8)**

any idea how to solve it? 
can you help me for this error?

**Comment by GunnarBaldursson** [comment]
Hello. Did you ever solve this problem?
 I am Having the same one.  Crashes Hoobs/Homebridge Randomly.
 
![178850766_825877404786197_8823388588097339844_n](https://user-images.githubusercontent.com/71457804/116807124-dd000000-ab20-11eb-8351-41c9fe2ef3b1.jpg)
